version: "3.8"

services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "6700:5432"
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres-db:/var/lib/postgresql/data

  mongo:
    image: mongo:latest
    container_name: mongo2
    restart: always
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo:/data/db
    ports:
      - "6100:27017"

volumes:
  postgres-db:
  mongo:
