version: "3.8"

services:
  app:
    build: .
    container_name: app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - mongo
    env_file:
      - ./.env

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "6500:5432"
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres-db:/var/lib/postgresql/data

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo:/data/db
    ports:
      - "6000:27017"

volumes:
  postgres-db:
  mongo:
