"""create table user

Revision ID: c5a49b8b3960
Revises: 
Create Date: 2022-12-30 14:50:16.957624

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c5a49b8b3960'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', postgresql.UUID(
                        as_uuid=True), nullable=False),
                    sa.Column('username', sa.String(), nullable=False),
                    sa.Column('full_name', sa.String(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('password', sa.String(), nullable=False),
                    sa.Column('photo', sa.String(), nullable=True),
                    sa.Column('verified', sa.Boolean(),
                              server_default='False', nullable=False),
                    sa.Column('verification_code', sa.String(), nullable=True),
                    sa.Column('password_reset_code',
                              sa.String(), nullable=True),
                    sa.Column('password_reset_code_expiry',
                              sa.DateTime(), nullable=True),
                    sa.Column('role', sa.String(),
                              server_default='user', nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('verification_code'),
                    sa.UniqueConstraint('password_reset_code')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
